"""``tests/fixtures/defects/`` 的读取与构造辅助（Phase 0 证据固化）。

真机采集的原始产物（hilog / faultlog / 截图 / ArkUI dump）体积大且不稳定，因此这里
把「样本来源与可靠性」显式写进每个 fixture 的文件头，并提供统一的读取入口，避免各
测试文件重复拼路径或重复造设备替身。
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from PIL import Image

from harmony_test_agent.models import (
    AnomalyFinding,
    AnomalyKind,
    CommandResult,
    ScreenSnapshot,
)
from harmony_test_agent.perception.normalizer import normalize_layout, page_path

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "defects"

BUNDLE = "com.zhihu.hmos"
OTHER_BUNDLE = "com.huawei.hmos.settings"


def fixture_text(name: str) -> str:
    """读取文本 fixture 原文（``hilog_*.txt`` / ``faultlog_index.txt``）。"""
    return (FIXTURES / name).read_text(encoding="utf-8")


def fixture_json(name: str) -> dict:
    """读取 ArkUI dump fixture。"""
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def fixture_path(name: str) -> Path:
    """返回 fixture 的绝对路径（截图 / layout 用）。"""
    return FIXTURES / name


def hilog_cppcrash() -> str:
    return fixture_text("hilog_cppcrash.txt")


def hilog_appfreeze() -> str:
    return fixture_text("hilog_appfreeze.txt")


def hilog_clean() -> str:
    return fixture_text("hilog_clean.txt")


def faultlog_index() -> str:
    return fixture_text("faultlog_index.txt")


#: 与 ``tests/fixtures/defects/faultlog_index.txt`` 中 ``com.zhihu.hmos`` 条目对应的
#: faultlog 头部内容（与既有 ``tests/fixtures/analysis/faultlog_cppcrash_head.txt`` 同族）。
FAULTLOG_CPPCRASH_HEAD = """\
Generated by HiviewDFX@OpenHarmony
================================================================
Device info:OpenHarmony-5.0.0
Build info:OpenHarmony-5.0.0.100
Fault modifier:cppcrash
Timestamp:2026-02-10 10:15:30.000
Pid:4321
Uid:20020001
Process name:com.zhihu.hmos
Reason: Signal:SIGSEGV(SEGV_MAPERR)@0x0000000000000000
Fault thread info:
Tid:4321, Name:com.zhihu.hmos
#00 pc 0000000000123456 /system/lib64/libark.so
#01 pc 0000000000654321 /system/lib64/libace.so
"""


def solid_png(path: Path, value: int = 255, size: tuple[int, int] = (1080, 2340)) -> Path:
    """把纯色截图写到 ``path``（``value=255`` 白屏、``value=0`` 黑屏）。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("L", size, value).save(path, format="PNG")
    return path


def textured_png(path: Path, *, size: tuple[int, int] = (1080, 2340)) -> Path:
    """写一张有内容的正常页面截图：左右分块 + 中部色带，确保 σ 远超白屏阈值。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    image = Image.new("L", size, 128)
    width, height = size
    for x in range(width):
        for y in range(0, height, 7):
            image.putpixel((x, y), (x * 31 + y * 17) % 256)
    image.save(path, format="PNG")
    return path


def snapshot_from_layout_fixture(
    path: Path,
    *,
    run_id: str = "run-defect",
    snapshot_id: str | None = None,
    image_path: Path | None = None,
    image_sha256: str | None = None,
) -> ScreenSnapshot:
    """把 ArkUI dump fixture 还原成 ``ScreenSnapshot``（宽高从根 bounds 推导）。"""
    layout = fixture_json(path.name)
    attrs = layout.get("attributes") or {}
    bounds = str(attrs.get("bounds") or "[0,0][1080,2340]")
    left, top, right, bottom = _bounds_tuple(bounds)
    width, height = max(1, right - left), max(1, bottom - top)
    image = image_path or path.with_suffix(".png")
    digest = image_sha256
    if digest is None:
        digest = hashlib.sha256(image.read_bytes()).hexdigest() if image.is_file() else f"digest-{path.stem}"
    return ScreenSnapshot(
        snapshot_id=snapshot_id or path.stem,
        run_id=run_id,
        image_path=image,
        image_sha256=digest,
        width=width,
        height=height,
        page_path=page_path(layout),
        hierarchy_path=path,
        elements=normalize_layout(layout, width, height),
    )


def _bounds_tuple(bounds: str) -> tuple[int, int, int, int]:
    """解析 ``[l,t][r,b]``；不可解析时退回全屏默认值。"""
    import re

    match = re.search(r"\[(-?\d+),(-?\d+)\]\[(-?\d+),(-?\d+)\]", bounds)
    if not match:
        return 0, 0, 1080, 2340
    return tuple(int(item) for item in match.groups())  # type: ignore[return-value]


class DefectFakeDevice:
    """缺陷检测用设备替身：前台应用、hilog、faultlog 与 UI dump 全部受控。

    只实现 ``analysis`` 链路真正调用的接口（``_run`` / ``collect_logs`` /
    ``collect_ui_hierarchy`` / ``current_foreground_app``），并逐项计数以便断言
    「无可疑时设备零调用」（G7）。
    """

    def __init__(
        self,
        *,
        foreground: str | None = BUNDLE,
        hilog: str = "",
        listing: str = "",
        head: str = "",
        hierarchy: dict | None = None,
        pidof: str = "4321",
    ) -> None:
        self.foreground_bundle = foreground
        self.hilog = hilog
        self.listing = listing
        self.head = head
        self.hierarchy = hierarchy
        self.pidof = pidof
        self.foreground_calls = 0
        self.collect_log_calls = 0
        self.hierarchy_calls = 0
        self.calls: list[tuple[str, ...]] = []

    # -- 设备合同 ----------------------------------------------------
    def _run(self, *args: str, timeout: float | None = None, device: bool = True) -> CommandResult:
        self.calls.append(tuple(args))
        stdout = ""
        if args[:2] == ("shell", "ls"):
            stdout = self.listing
        elif args[:2] == ("shell", "head"):
            stdout = self.head
        elif args[:2] == ("shell", "pidof"):
            stdout = self.pidof
        return CommandResult(command="hdc " + " ".join(args), args=list(args), returncode=0, stdout=stdout)

    def collect_logs(self, output_path: Path) -> CommandResult:
        self.collect_log_calls += 1
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(self.hilog, encoding="utf-8")
        return CommandResult(
            command="hdc shell hilog -x",
            args=["shell", "hilog", "-x"],
            returncode=0,
            stdout=self.hilog,
        )

    def collect_ui_hierarchy(self) -> dict:
        self.hierarchy_calls += 1
        if self.hierarchy is None:
            raise RuntimeError("no hierarchy available")
        return self.hierarchy

    def current_foreground_app(self):
        self.foreground_calls += 1
        if self.foreground_bundle is None:
            return None
        from harmony_test_agent.targets import ForegroundApp

        return ForegroundApp(bundle_name=self.foreground_bundle, ability_name="EntryAbility", window_type="main")

    # -- 断言辅助 ----------------------------------------------------
    @property
    def device_calls(self) -> int:
        """除 ``current_foreground_app`` 之外的设备调用总数（G7 的机器证明）。"""
        return len(self.calls) + self.collect_log_calls + self.hierarchy_calls


def finding(
    kind: AnomalyKind = AnomalyKind.PAGE_UNRESPONSIVE,
    *,
    severity: str = "warning",
    summary_zh: str = "页面无响应",
    source: str = "screenshot",
    **overrides,
) -> AnomalyFinding:
    """构造一条最小 finding，避免每个测试重复手写字段。"""
    payload = {
        "kind": kind,
        "severity": severity,
        "summary_zh": summary_zh,
        "source": source,
        **overrides,
    }
    return AnomalyFinding(**payload)
